In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('Colab_Files_Data')

Mounted at Colab_Files_Data


In [25]:
df = pd.read_csv('/content/Colab_Files_Data/MyDrive/Colab Notebooks/Colab_Files_Data/34_Feature_Transformation/Categorical_Encoding/customer.csv')

In [26]:
df.sample(5)

age  gender   review education purchased
2    70  Female     Good        PG        No
49   25  Female     Good        UG        No
29   83  Female  Average        UG       Yes
10   98  Female     Good        UG       Yes
38   45  Female     Good    School        No

In [27]:
df = df.iloc[:,1:]

In [28]:
df.head(10)

gender   review education purchased
0  Female  Average    School        No
1  Female     Poor        UG        No
2  Female     Good        PG        No
3  Female     Good        PG        No
4  Female  Average        UG        No
5  Female  Average    School       Yes
6    Male     Good    School        No
7  Female     Poor    School       Yes
8  Female  Average        UG        No
9    Male     Good        UG       Yes

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [31]:
# OHE
ohe=OneHotEncoder(drop='first',sparse=False)
df_new=pd.get_dummies(df['gender'],drop_first=True,dtype='int')
# OR
df_new.astype('int').head(5)

Male
0     0
1     0
2     0
3     0
4     0

In [9]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform(df)
oe.categories_     #### gives the order of the category numbers (0,1,2,,......n)


[array(['Average', 'Good', 'Poor'], dtype=object),
 array(['PG', 'School', 'UG'], dtype=object),
 array(['No', 'Yes'], dtype=object)]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,:2],df.iloc[:,-1])

In [ ]:
X_train

review education
11     Good        UG
44  Average        UG
13  Average    School
5   Average    School
15     Poor        UG
1      Poor        UG
12     Poor    School
26     Poor        PG
8   Average        UG
23     Good    School
39     Poor        PG
42     Good        PG
35     Poor    School
6      Good    School
25     Good    School
24  Average        PG
3      Good        PG
14     Poor        PG
43     Poor        PG
47     Good        PG
20  Average    School
30  Average        UG
19     Poor        PG
40     Good    School
34  Average    School
31     Poor    School
41     Good        PG
7      Poor    School
37  Average        PG
45     Poor        PG
36     Good        UG
22     Poor        PG
21  Average        PG
4   Average        UG
28     Poor    School
29  Average        UG
17     Poor        UG

In [ ]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])      ### for ordinal data specify your category rankings

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train = oe.transform(X_train)

In [ ]:
X_train

array([[2., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[2., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder  ## same as ordinal encoding with the difference of we don't specify order here

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_               ######################### hows the encoding

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
!pip install category_encoders
import category_encoders as ce
t = ce.TargetEncoder(cols=['gender'])
t.fit_transform(df['gender'],df['age'])