### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
# isin
# arange vs linspace (arange start,end,step,linspace_start,num_of_elements linearly space elements)

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
# np.arange # np.arange is a function from the NumPy library in Python.
# It is used to generate a sequence of numbers within a specified range. The syntax is as follows.
# np.arange([start,] stop[, step,], dtype=None)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.arange(2,22,6,)

array([ 2,  8, 14, 20])

In [ ]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.ones((1,1))                                                #############(()) for multiinput [] in pandas

array([[1.]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((5,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# np.random
np.random.random((5,2))

array([[0.85409684, 0.39959491],
       [0.51745696, 0.70506662],
       [0.28138234, 0.64011359],
       [0.31777748, 0.91221308],
       [0.51554046, 0.94825843]])

In [ ]:
np.random.randint(10,100,10)

array([10, 34, 75, 61, 14, 40, 68, 48, 59, 62])

In [ ]:
np.linspace(-10,10,10)       ## how it differs from arange  1. arange takes range and step where linspace takes range and number of elements you want

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.linspace
a=np.linspace(-10,10,10,dtype=int).reshape(5,2)
a

array([[-10,  -8],
       [ -6,  -4],
       [ -2,   1],
       [  3,   5],
       [  7,  10]])

In [ ]:
###
np.isin(a,-10)         ################

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [ ]:
a[np.isin(a,-6)]        ################## Very Important

array([-6])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size                                    ############# no fo elements
print(a2.size)

12


In [ ]:
# itemsize
a3.itemsize                                     ############# memory

8

In [ ]:
a=np.array([1,2,3])
print(a.itemsize)                       ########
print(a.size)                           #######

8
3


In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32) #################################  changing the datatypes unlike dtype where we define the data type while creating the array only

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a3.astype(float)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scalar operations
# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[94., 36., 85.],
       [ 6., 54., 93.],
       [99., 63., 40.]])

In [ ]:
a1 = np.random.random((3,3))
a1

array([[0.53282496, 0.24444681, 0.17073378],
       [0.30179751, 0.25777568, 0.17583701],
       [0.53787931, 0.45211634, 0.69754803]])

In [ ]:
np.round(a1*10)

array([[5., 2., 2.],
       [3., 3., 2.],
       [5., 5., 7.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row  row is superior that is why it takes 1
np.prod(a1,axis=0)

array([0.08649382, 0.02848896, 0.02094131])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([0.02441173, 0.00272421, 0.0103429 ])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[0.50796872, 0.24201962, 0.16990551],
       [0.29723696, 0.25493036, 0.1749323 ],
       [0.5123159 , 0.43687021, 0.64234038]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[1.70373851, 1.27691475, 1.18617492],
       [1.35228738, 1.29404851, 1.19224371],
       [1.7123716 , 1.57163478, 2.00882109]])

In [ ]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[85., 41., 27.],
       [70., 37., 28.]])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]


array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
np.where(a2==2)     ## Gives you the index positions

(array([0]), array([2]))

In [ ]:
a2=[1,2,3]
a2=np.array(a2)
np.where(a2==3)

(array([2]),)

In [ ]:
a2

array([1, 2, 3])

In [ ]:
for i in a2:
  print(i)

1
2
3


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:            ############################ prints one by one internal array
  print(i)
  break

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a3=np.random.randint(1,90,50)

In [ ]:
np.ravel(a3)                        ##################### 1D array ##################

array([62, 17, 47,  1, 71, 79, 86, 35, 22, 72, 14, 89, 88, 44, 14, 52, 89,
       47,  6, 59, 68, 31, 11, 47, 32, 29, 76, 51, 28, 50, 21, 25, 74, 17,
       74,  2, 20, 22, 42, 10, 44, 52, 14,  3, 19, 25, 57, 24, 83, 68])

In [ ]:
np.nditer(a3)

In [ ]:
for i in np.nditer(a3): ########################### makes it into a 1-D array and iterates like ravel ##############
##     sort of same of directly using a loop just more efficient
  print(i)

62
17
47
1
71
79
86
35
22
72
14
89
88
44
14
52
89
47
6
59
68
31
11
47
32
29
76
51
28
50
21
25
74
17
74
2
20
22
42
10
44
52
14
3
19
25
57
24
83
68


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T        #####################

array([1, 2, 3])

In [ ]:
a=np.arange(1,19).reshape(6,3)
b=np.arange(19,37).reshape(6,3)

In [ ]:
# ravel
a3.ravel()

array([85, 27, 83, 40, 23, 54, 63, 21, 24, 50, 88, 65,  4, 14, 32, 64, 68,
       18, 77, 31,  1,  7, 64, 62, 83, 73, 37, 26, 52, 80, 25, 23,  3, 46,
       57, 87, 70, 17, 19,  9, 17, 17, 15, 49, 60, 21, 55, 42, 21, 31])

In [ ]:
a1=[1,2,3]

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c=np.hstack((a4,a5))
d=np.vstack((a4,a5))
print(c)
print()
print(d)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
c=np.hstack((a,b))                      ############ one arguments not two ######################
print(c)

[[ 1  2  3 19 20 21]
 [ 4  5  6 22 23 24]
 [ 7  8  9 25 26 27]
 [10 11 12 28 29 30]
 [13 14 15 31 32 33]
 [16 17 18 34 35 36]]


In [ ]:
np.hsplit(c,2)

[array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 array([[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]])]

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
d=np.vstack((a4,a5))
np.vsplit(d,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.vsplit(d,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

### Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]