In [3]:
# Sort
# Append adds elements at the end
# Concatenate adds two arrays
# np.where - for single condition returns the indices and with conditins we replaces the values belong to those filtered indeces by conditional values.
# a.reshape(-1,4) # -1 is the placeholder in the specified dimension which will be calculated based on the no.of elements

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [4]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([86, 54, 80,  7, 85,  5, 31, 88,  2, 60, 62, 72, 85, 86, 41])

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[87, 99,  3, 31],
       [29, 71, 24, 62],
       [14, 70, 20, 35],
       [88, 64, 43, 48],
       [93, 67, 25, 88],
       [53, 30,  5, 67]])

In [6]:
np.sort(b)[::-1]

array([[ 5, 30, 53, 67],
       [25, 67, 88, 93],
       [43, 48, 64, 88],
       [14, 20, 35, 70],
       [24, 29, 62, 71],
       [ 3, 31, 87, 99]])

In [7]:
np.sort(b)[::-1]

array([[ 5, 30, 53, 67],
       [25, 67, 88, 93],
       [43, 48, 64, 88],
       [14, 20, 35, 70],
       [24, 29, 62, 71],
       [ 3, 31, 87, 99]])

In [8]:
np.sort(b,axis=0)

array([[14, 30,  3, 31],
       [29, 64,  5, 35],
       [53, 67, 20, 48],
       [87, 70, 24, 62],
       [88, 71, 25, 67],
       [93, 99, 43, 88]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# code
np.append(a,200)

array([ 86,  54,  80,   7,  85,   5,  31,  88,   2,  60,  62,  72,  85,
        86,  41, 200])

In [10]:
np.append(a,np.array([ 82,  29,  78,  92,   2,  53,  17,   3,  68,  84,  19,  56,   9,
        34,  66, 200]))

array([ 86,  54,  80,   7,  85,   5,  31,  88,   2,  60,  62,  72,  85,
        86,  41,  82,  29,  78,  92,   2,  53,  17,   3,  68,  84,  19,
        56,   9,  34,  66, 200])

In [11]:
b

array([[87, 99,  3, 31],
       [29, 71, 24, 62],
       [14, 70, 20, 35],
       [88, 64, 43, 48],
       [93, 67, 25, 88],
       [53, 30,  5, 67]])

In [ ]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
a=a.reshape(5,2)

In [ ]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.append(a,np.array([[11,12],[13,14]]).reshape(-1,2),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [12]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[8.70000000e+01, 9.90000000e+01, 3.00000000e+00, 3.10000000e+01,
        5.56666174e-01],
       [2.90000000e+01, 7.10000000e+01, 2.40000000e+01, 6.20000000e+01,
        5.28481728e-01],
       [1.40000000e+01, 7.00000000e+01, 2.00000000e+01, 3.50000000e+01,
        9.95871183e-01],
       [8.80000000e+01, 6.40000000e+01, 4.30000000e+01, 4.80000000e+01,
        7.52608890e-01],
       [9.30000000e+01, 6.70000000e+01, 2.50000000e+01, 8.80000000e+01,
        1.16732622e-02],
       [5.30000000e+01, 3.00000000e+01, 5.00000000e+00, 6.70000000e+01,
        6.81594596e-01]])

In [ ]:
import numpy as np

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[61],
       [99],
       [79],
       [17],
       [52],
       [19],
       [31],
       [68],
       [80],
       [79],
       [77],
       [57],
       [83],
       [61],
       [82]])

### np.where

The numpy.where() function returns the **indices** of elements in an input array where the given condition is satisfied when if else is not given.
On giving if else it return the elements based on the conditions

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([61, 99, 79, 17, 52, 19, 31, 68, 80, 79, 77, 57, 83, 61, 82])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  4,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [ ]:
np.where(a>0) # only way to get indexes

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [ ]:
np.where(a>50,9,a)

array([ 9,  9,  9, 17,  9, 19, 31,  9,  9,  9,  9,  9,  9,  9,  9])

In [ ]:
np.where(a>50,a,0)

array([61, 99, 79,  0, 52,  0,  0, 68, 80, 79, 77, 57, 83, 61, 82])

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0, 17,  0, 19, 31,  0,  0,  0,  0,  0,  0,  0,  0])

In [ ]:
np.where(a%2 == 0,0,a)

array([61, 99, 79, 17,  0, 19, 31,  0,  0, 79, 77, 57, 83, 61,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([61, 99, 79, 17, 52, 19, 31, 68, 80, 79, 77, 57, 83, 61, 82])

In [ ]:
np.argmax(a)

1

In [ ]:
b

array([[42, 94, 99, 57],
       [46, 90, 59, 87],
       [31, 57,  9, 38],
       [88, 28, 14, 98],
       [89, 26, 84, 47],
       [55, 59, 14, 77]])

In [ ]:
np.argmax(b,axis=0)

array([4, 0, 0, 3])

In [ ]:
np.argmax(b,axis=1)

array([2, 1, 1, 3, 0, 3])

In [ ]:
# np.argmin
np.argmin(a)

3

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([61, 99, 79, 17, 52, 19, 31, 68, 80, 79, 77, 57, 83, 61, 82])

In [ ]:
np.cumsum(a)

array([ 61, 160, 239, 256, 308, 327, 358, 426, 506, 585, 662, 719, 802,
       863, 945])

In [ ]:
b

array([[42, 94, 99, 57],
       [46, 90, 59, 87],
       [31, 57,  9, 38],
       [88, 28, 14, 98],
       [89, 26, 84, 47],
       [55, 59, 14, 77]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 42, 136, 235, 292],
       [ 46, 136, 195, 282],
       [ 31,  88,  97, 135],
       [ 88, 116, 130, 228],
       [ 89, 115, 199, 246],
       [ 55, 114, 128, 205]])

In [ ]:
np.cumsum(b)

array([ 35,  99, 191, 206, 261, 271, 329, 369, 377, 454, 548, 574, 600,
       679, 705, 708, 738, 819, 857, 874, 890, 928, 949, 966])

In [ ]:
# np.cumprod
np.cumprod(a)

array([       1,        2,        6,       24,      120,      720,
           5040,    35280,   105840,   423360,   846720,  3386880,
       20321280])

In [ ]:
a

[1, 2, 3, 4, 5, 6, 7, 7, 3, 4, 2, 4, 6]

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

[1, 2, 3, 4, 5, 6, 7, 7, 3, 4, 2, 4, 6]

In [ ]:
np.percentile(a,50)

4.0

In [ ]:
np.median(a)

4.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([14, 81, 92,  6, 22, 40, 79, 40, 49, 78, 20, 51, 78, 75, 89])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([14, 81, 92,  6, 22, 40, 79, 40, 49, 78, 20, 51, 78, 75, 89])

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.isin(a,[3]).sum()

1

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([40, 40, 20])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a=np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
import numpy as np
np.flip(np.sort(a)[::-1])

array([ 2,  5,  9, 11, 21, 28, 30, 37, 38, 50, 53, 68, 78, 92, 94])

In [ ]:
np.sort(a)[::-1]

array([7, 7, 6, 6, 5, 4, 4, 4, 3, 3, 2, 2, 1])

In [ ]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [ ]:
b

array([[35, 64, 92, 15],
       [55, 10, 58, 40],
       [ 8, 77, 94, 26],
       [26, 79, 26,  3],
       [30, 81, 38, 17],
       [16, 38, 21, 17]])

In [ ]:
np.flip(b,axis=1)

array([[15, 92, 64, 35],
       [40, 58, 10, 55],
       [26, 94, 77,  8],
       [ 3, 26, 79, 26],
       [17, 38, 81, 30],
       [17, 21, 38, 16]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.delete(a,[0,2,4])

array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   2,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

In [ ]:
# Multi-dimensional arrays
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[3, 4], [5, 6]])

# Intersection of arr3 and arr4 (result will be 1D)
intersection_multi = np.intersect1d(arr3, arr4)
print(intersection_multi)  # Output: [3 4]


[3 4]


### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [1]:
# code
a

NameError: name 'a' is not defined

In [2]:
np.clip(a,a_min=25,a_max=75)                            ###

NameError: name 'np' is not defined

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:
# 25. np.allclose and equals