<a href="https://colab.research.google.com/github/harshalzate/ML/blob/main/PYTHON/NOTES/17_0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ndarray attributes

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

In [ ]:
# nditer is more efficient and productive way of iterating over an array.
# there are two main features falgs and op_flags which provide extra features and methods of iteration

In [ ]:
# for flags
# 1. bufferedd
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['float64']):
  print(i,type(i))

In [ ]:
arr

In [ ]:
# 2 c_index = row wise index
i=np.nditer(arr,flags = ['c_index'])
for x in i:
  print(x,i.index)

In [ ]:
#3 column wise index
i=np.nditer(arr,flags = ['f_index'])
for x in i:
  print(x,i.index)

In [ ]:
# multi_index
i=np.nditer(arr,flags = ['multi_index'])
for x in i:
  print(x,i.multi_index)

In [ ]:
# common_dtpes
x = np.array([[1,2,3],[4,5,6]],dtype = np.int32)
y = (x+1).astype('float64')
for a,b in np.nditer([x,y]):
  print(a,b)

for x, y in np.nditer([arr1, arr2], flags=['common_dtype','buffered']):
    print(f"Integer: {x}, Float: {y}, Common Type: {x + y}")

In [ ]:
# Difference between flag and op_flag with the implication of the methods, is it sepcific to operand or gloabl
# op_flag is about the treatment of the individual operand( what is oeprand : an array)


# op_flag

#1. readonly
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr, op_flags=['readonly']):
    print(x, end=' ')
# Output: 1 2 3 4 5 6

In [ ]:
arr

In [ ]:
for x in np.nditer(arr,op_flags =['readonly']):
  x=x+1
  print(x)

In [ ]:
arr

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
with np.nditer(arr, op_flags=['readwrite']) as it:
    for x in it:
        x[...] = x * 2  # Double each element
print(arr)
# Output: [[ 2  4  6]
#          [ 8 10 12]]

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in np.nditer(arr, op_flags=['readwrite']):
  x[...] = x * 2  # Double each element
print(arr)
# Output: [[ 2  4  6]
#          [ 8 10 12]]

In [ ]:
# Ellipsis
arr[...]

In [ ]:
# 3 writeonly
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in np.nditer(arr, op_flags=['writeonly']):
  x[...] = x * 2  # Double each element
print(arr)
# Output: [[ 2  4  6]
#          [ 8 10 12]]