In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
from google.colab import drive
drive.mount('Colab_Files_Data')

Mounted at Colab_Files_Data


In [ ]:
df=pd.read_csv('/content/Colab_Files_Data/MyDrive/Colab Notebooks/Colab_Files_Data/Naive_Bayes/IMDB Dataset.csv')

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
# One review
df['review'].str.split()

0        [One, of, the, other, reviewers, has, mentione...
1        [A, wonderful, little, production., <br, /><br...
2        [I, thought, this, was, a, wonderful, way, to,...
3        [Basically, there's, a, family, where, a, litt...
4        [Petter, Mattei's, "Love, in, the, Time, of, M...
                               ...                        
49995    [I, thought, this, movie, did, a, down, right,...
49996    [Bad, plot,, bad, dialogue,, bad, acting,, idi...
49997    [I, am, a, Catholic, taught, in, parochial, el...
49998    [I'm, going, to, have, to, disagree, with, the...
49999    [No, one, expects, the, Star, Trek, movies, to...
Name: review, Length: 50000, dtype: object

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [ ]:
df=df.sample(10000)

In [ ]:
df.shape

(10000, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 36627 to 47127
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB


In [ ]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [ ]:
df.head()

review  sentiment
36627  This film, by Oscar Petersson, is unique. Its ...          0
7388   Love this little film, that reminds me somewha...          1
30562  It's a strange, yet somehow impressive story, ...          1
32491  Relish every moment of this languorous spectac...          1
4787   The sight of Kareena Kapoor in a two-piece bik...          0

In [ ]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'It\'s a strange, yet somehow impressive story, about love. Personnaly, I never run over such a twist-off story in real life. But, I can image there is.It\'s a story that promises to be "sick" from the title. But, after I watch it, I didn\'t get this feeling of "sickness" which I would surely have regarding society rules. It\'s something beautiful in this movie... something impressive...which I cannot contradict using any moral or society rules.The movie focuses mostly on relation between Kiki and Alex. You can see how this relation starts, evolves and finally ends. You feel the moment when this love blossoms, the first whispers, touchings. You feel the connection. And no moment I though this is immoral. You even hope it will not break in the end....it cannot break...it\'s not right. You feel the pain of being hart broken in the end...But,I need also to add a negative spin to this comment...I don\'t know if the story is not somehow *showed* to give the feeling that these relations are 

In [ ]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [ ]:
df['review']=df['review'].apply(clean_html)

In [ ]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [ ]:
df['review']=df['review'].apply(convert_lower)

In [ ]:
# function to remove special characters

def remove_special(text):
    x=''

    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [ ]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [ ]:
df['review']=df['review'].apply(remove_special)

In [ ]:
# Remove the stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
df

review  sentiment
36627  this film  by oscar petersson  is unique  its ...          0
7388   love this little film  that reminds me somewha...          1
30562  it s a strange  yet somehow impressive story  ...          1
32491  relish every moment of this languorous spectac...          1
4787   the sight of kareena kapoor in a two piece bik...          0
...                                                  ...        ...
31014  in my opinion  this is a good example of the m...          1
28045  if you re watching this without an inkling of ...          0
8795   this show proved to be a waste of 30 minutes o...          0
7930   i have just watched the movie for the first ti...          0
47127  no doubt  when madonna and guy ritchie married...          0

[10000 rows x 2 columns]

In [ ]:
def remove_stopwords(text):
    x=[]
    for i in text.split():

        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [ ]:
df['review']=df['review'].apply(remove_stopwords)

In [ ]:
df

review  sentiment
36627  [film, oscar, petersson, unique, uniqueness, l...          0
7388   [love, little, film, reminds, somewhat, origin...          1
30562  [strange, yet, somehow, impressive, story, lov...          1
32491  [relish, every, moment, languorous, spectacle,...          1
4787   [sight, kareena, kapoor, two, piece, bikini, t...          0
...                                                  ...        ...
31014  [opinion, good, example, movie, could, much, b...          1
28045  [watching, without, inkling, idea, story, quit...          0
8795   [show, proved, waste, 30, minutes, precious, d...          0
7930   [watched, movie, first, time, wanted, watch, l...          0
47127  [doubt, madonna, guy, ritchie, married, though...          0

[10000 rows x 2 columns]

In [ ]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z


In [ ]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [ ]:
df['review']=df['review'].apply(stem_words)

In [ ]:
df

review  sentiment
36627  [film, oscar, petersson, uniqu, uniqu, lie, st...          0
7388   [love, littl, film, remind, somewhat, origin, ...          1
30562  [strang, yet, somehow, impress, stori, love, p...          1
32491  [relish, everi, moment, languor, spectacl, mus...          1
4787   [sight, kareena, kapoor, two, piec, bikini, th...          0
...                                                  ...        ...
31014  [opinion, good, exampl, movi, could, much, bet...          1
28045  [watch, without, inkl, idea, stori, quit, surp...          0
8795   [show, prove, wast, 30, minut, preciou, dvr, h...          0
7930   [watch, movi, first, time, want, watch, like, ...          0
47127  [doubt, madonna, guy, ritchi, marri, thought, ...          0

[10000 rows x 2 columns]

In [ ]:
# Join back
def join_back(list_input):
    return " ".join(list_input)


In [ ]:
df['review']=df['review'].apply(join_back)

In [ ]:
df['review']

36627    film oscar petersson uniqu uniqu lie stori sin...
7388     love littl film remind somewhat origin japanes...
30562    strang yet somehow impress stori love personna...
32491    relish everi moment languor spectacl music mat...
4787     sight kareena kapoor two piec bikini thing wak...
                               ...                        
31014    opinion good exampl movi could much better sho...
28045    watch without inkl idea stori quit surpris eve...
8795     show prove wast 30 minut preciou dvr hard driv...
7930     watch movi first time want watch like drew bar...
47127    doubt madonna guy ritchi marri thought would h...
Name: review, Length: 10000, dtype: object

In [ ]:
X=df.iloc[:,0:1].values

In [ ]:
X.shape

(10000, 1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)

In [ ]:
X=cv.fit_transform(df['review']).toarray()

In [ ]:
X.shape

(10000, 2500)

In [ ]:
X[0].mean()

0.0356

In [ ]:
y=df.iloc[:,-1].values

In [ ]:
y.shape

(10000,)

In [ ]:
# X,y
# Training set
# Test Set(Already know the result)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
X_train.shape

(8000, 2500)

In [ ]:
X_test.shape

(2000, 2500)

In [ ]:
y_train.shape

(8000,)

In [ ]:
y_test.shape

(2000,)

In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [ ]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [ ]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [ ]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [ ]:
y_test.shape

(2000,)

In [ ]:
y_pred1.shape

(2000,)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.727
Multinomial 0.843
Bernaulli 0.8465


In [ ]:
df = pd.read_csv('https://gist.githubusercontent.com/DiogoRibeiro7/c6590d0cf119e87c39e31c21a9c0f3a8/raw/4a8e3da267a0c1f0d650901d8295a5153bde8b21/PlayTennis.csv')

In [ ]:
df

Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [ ]:
pd.crosstab(df['Outlook'], df['Play Tennis'],normalize='columns').stack().to_dict()

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222}

In [ ]:
D = {}
for i in ['Outlook','Temperature',	'Humidity',	'Wind']:
  D.update(pd.crosstab(df[i], df['Play Tennis'],normalize='columns').stack().to_dict())

In [ ]:
D

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222,
 ('Cool', 'No'): 0.2,
 ('Cool', 'Yes'): 0.3333333333333333,
 ('Hot', 'No'): 0.4,
 ('Hot', 'Yes'): 0.2222222222222222,
 ('Mild', 'No'): 0.4,
 ('Mild', 'Yes'): 0.4444444444444444,
 ('High', 'No'): 0.8,
 ('High', 'Yes'): 0.3333333333333333,
 ('Normal', 'No'): 0.2,
 ('Normal', 'Yes'): 0.6666666666666666,
 ('Strong', 'No'): 0.6,
 ('Strong', 'Yes'): 0.3333333333333333,
 ('Weak', 'No'): 0.4,
 ('Weak', 'Yes'): 0.6666666666666666}

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Example documents
documents = ["This is the first document.",
             "This document is the second document.",
             "And this is the third one.",
             "Is this the first document?"]

# Create an instance of CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the documents into a Bag of Words representation
X = vectorizer.fit_transform(documents)

# Get the feature names (words) in the vocabulary
feature_names = vectorizer.get_feature_names_out()

# Convert the Bag of Words representation to a dense NumPy array for easier inspection
dense_matrix = X.toarray()

# Print the results
print("Feature Names (Vocabulary):", feature_names)
print("Bag of Words Representation:")
print(dense_matrix)


Feature Names (Vocabulary): ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
Bag of Words Representation:
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = ["This is the first document.",
             "This document is the second document.",
             "And this is the third one.",
             "Is this the first document?"]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)
X.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])